// version.js — sichtbarer Build-Stempel (Deploy-Kontrolle) + App-Version & Changelog.
export const BUILD = "2026-10-04-v2.14";
export const APP_VERSION = "2.14";

// Changelog (neueste zuerst) — im Guide angezeigt.
export const CHANGELOG = [
  { v: "v2.14", txt: "Freunde schreiben mit: Unter 🛒 Einkauf → „🔗 Freunde-Link“ erstellst du einen Link, den du per WhatsApp & Co. teilst. Wer ihn öffnet, sieht deine offenen Artikel und kann etwas hinzufügen — ohne App und ohne Google-Konto. Die Vorschläge landen automatisch auf deiner Liste (und bei deinem Partner), sobald du die App öffnest, mit einem kleinen „von Anna“ dahinter. Neuer Link oder ausschalten jederzeit möglich; ausschalten löscht alles auf dem Server." },
  { v: "v2.13", txt: "Zutaten mit Symbolen: In der Rezeptansicht, im Kochmodus und bei den Vorrats-Chips im Lager steht jetzt vor jeder Zutat ihr Symbol — alles aus einem gemeinsamen Katalog, der auch die Einkaufsliste sortiert. Einzahl wird jetzt erkannt („1 Zwiebel“ landet im Gemüse-Gang statt unter „Aus Rezepten“). Rezept erfassen: Fortschritt und Meldungen erscheinen direkt bei der Karte, die du angetippt hast; URL geht auch mit Enter. „KI-Ideen“ richten sich nach deinem Koch-Profil (Ernährung, Portionen, Ausstattung), und erfasste Rezepte bekommen 🛒-Marker für fehlende Zutaten. Fehler behoben: „Bearbeiten“ in der Sammel-Erfassung speicherte das Rezept doppelt." },
  { v: "v2.12", txt: "Neue Leiste unten: Rezepte, Lager, Einkauf, Plan und KI-Assistent sind jetzt mit einem Daumen-Tipp erreichbar — von überall. Der Einkauf-Tab zeigt, wie viele Artikel noch offen sind (auch wenn dein Partner etwas hinzufügt). Nochmal auf den aktiven Tab tippen scrollt nach oben. Swipe-Match, Rezept erfassen, Einstellungen, Features & Versionen und Export findest du weiter im ☰-Menü. Im Kochmodus und beim Tippen verschwindet die Leiste." },
  { v: "v2.11", txt: "Geteilte Einkaufsliste repariert: Gelöschte und abgehakte Artikel kommen jetzt zuverlässig beim Partner an (vorher tauchten gelöschte wieder auf), und die Liste wird nicht mehr bei jedem Abgleich neu geschrieben. „Partner verbinden“ funktioniert wieder (die Google-Dateiauswahl wurde nie geladen). Neue Sync-Karte zeigt, wo deine Liste liegt und wann sie zuletzt abgeglichen wurde — mit Schritt-für-Schritt-Anleitung zum Teilen. Lesbar im dunklen Design. Artikel aus Rezepten erscheinen in deiner App-Sprache." },
  { v: "v2.10.1", txt: "Fehlerbehebung: Die App startete nach dem letzten Update nicht (leerer Bildschirm). Behoben — ein neuer automatischer Test verhindert, dass so etwas wieder live geht." },
  { v: `v2.10`, txt: `Einkaufsliste mit Partner teilen: Verbinde deine Liste über Google Drive — beide sehen dieselben Artikel und können gleichzeitig hinzufügen. Aktualisieren-Knopf holt den neuesten Stand.` },
  { v: `v2.9`, txt: `Küche, Saison und „Zuletzt gekocht” erscheinen jetzt in der gewählten App-Sprache — die Filter-Chips im Kochbuch und die Detailansicht zeigen z. B. auf Englisch „Italian” statt „Italienisch” und „May 2026” statt „Mai 2026”.` },
  { v: `v2.8`, txt: `Einkaufsliste teilen: Tippe auf „📤 Teilen” und die Liste landet als formatierten Text in jeder Messenger-App oder in der Zwischenablage — nach Supermarkt-Gang sortiert, erledigte Artikel mit ✓ markiert.` },
  { v: `v2.7`, txt: `Sicherer beim Synchronisieren: Wenn du etwas offline änderst und die Daten in der Cloud sich inzwischen ebenfalls geändert haben, wird deine lokale Änderung nicht mehr stillschweigend überschrieben — die App behält sie und meldet „Konflikt”, statt sie zu verlieren. Außerdem barrierefreier: alle Symbol-Knöpfe (Schließen, Entfernen, +/− auf der Einkaufsliste) haben jetzt größere Tippflächen und Vorlesehilfen.` },
  { v: "v2.6", txt: "Tippe oben links auf das 🍳-Symbol, um von überall zurück zur Startseite (Kochbuch) zu springen. Die Kopfzeile ist jetzt auf allen Bildschirmen einheitlich und barrierefreier (größere Tippflächen, Vorlesehilfen)." },
  { v: "v2.5", txt: "Neu im KI-Assistenten: „🥕 Aus Vorrat kochen“ schlägt Gerichte vor, die fast nur das brauchen, was du schon im Vorrat und Kühlschrank hast — frische Sachen werden bevorzugt verwertet. Außerdem sind die KI-Funktionen jetzt ehrlich: ohne Schlüssel oder offline erklären Assistent, Erfassung und Kühlschrank-Scan klar, warum sie gerade pausieren — statt einfach zu verschwinden oder fehlzuschlagen." },
  { v: "v2.4", txt: "Mehrfach-Filter: Du kannst jetzt mehrere Filter gleichzeitig anwählen. Innerhalb einer Gruppe gilt ODER (z. B. Pasta ODER Auflauf), und über die Gruppen hinweg wählst du mit dem UND/ODER-Schalter, ob alle oder irgendein Filter passen muss. Küche und Saison sind als Mehrfach-Auswahl ins „Mehr Filter“-Panel gewandert; eine Trefferanzeige zählt live mit, und „Filter zurücksetzen“ räumt alles weg." },
  { v: "v2.3", txt: "Dänisch (DA) als vierte Oberflächen-Sprache. Die Basis-Rezepte (die mitgelieferten ~105) erscheinen jetzt in der gewählten Sprache — Kategorien, Namen, Zutaten, Schritte und Tipps. Selbst hinzugefügte Rezepte bleiben in ihrer Eingabesprache. Die Einkaufsliste behält dabei Symbole und Gang-Sortierung in jeder Sprache." },
  { v: "v2.2", txt: "Erfassung zeigt jetzt klar an, dass die KI liest & baut; Foto wird nach dem Speichern zurückgesetzt. Neu: mehrere Rezepte auf einmal einfügen/generieren. Koch-Profil für die KI frei editierbar (Einstellungen). Lager: Artikel per Symbol-Katalog hinzufügen wie auf der Einkaufsliste. Einkaufsliste: „Alles löschen“ mit Rückgängig + Sortierung (Supermarkt/A–Z)." },
  { v: "v2.1", txt: "Mehrsprachig (DE/EN/ES), Foto- & URL-Rezepterfassung (KI), Lager mit Kühlschrank-Scan, In-App-Guide." },
  { v: "v2.0", txt: "Offline-first Rebuild: Kochbuch, Kochmodus, Wochenplan, Einkaufsliste, KI-Assistent (BYOK)." },
];
